version: 2.1

workflows:
  SIG:
    jobs:

      - polaris:
          context:
            - Polaris

jobs:


  polaris:
    docker:
      - image: circleci/openjdk:11-jdk
    environment:
      BLDCMD: 'mvn -B package -DskipTests'
    steps:
      - checkout
      - run:
          name: Polaris
          command: |
            curl -fLOsS $POLARIS_SERVER_URL/api/tools/polaris_cli-linux64.zip
            unzip -d /tmp -jo polaris_cli-linux64.zip
            /tmp/polaris --co project.name=chuckaude-$CIRCLE_PROJECT_REPONAME analyze -w -- $BLDCMD
